use_frameworks!

platform :ios, '8.0'

target 'HKIJKVideo_Example' do
  pod 'HKIJKVideo', :path => '../'

  target 'HKIJKVideo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
